require("general.reloads")
require("general.options")
require("general.autocmds")
require("general.commands")
require("general.variables")
require("general.keybinds")
require("general.functions")
require("general.highlights")
