Variable.g({
	coc_node_path = tostring(os.getenv("HOME")) .. "/.asdf/installs/nodejs/17.2.0/bin/node",
	coc_global_extensions = {
		"coc-clangd",
		"coc-css",
		"coc-db",
		"coc-ember",
		"coc-eslint",
		"coc-flutter-tools",
		"coc-go",
		"coc-html",
		"coc-java",
		"coc-java-debug",
		"coc-jest",
		"coc-marketplace",
		"coc-prettier",
		"coc-pyright",
		"coc-rls",
		"coc-rust-analyzer",
		"coc-solargraph",
		"coc-sumneko-lua",
		"coc-tsserver",
		"coc-vetur",
		"coc-vimlsp",
	},
})
